title: "Michael MacDonagh"
description: "Mike Mac Donagh's Blog and Portfolio of various Side Projects"
baseurl: "" # leave empty for GitHub Pages with custom domain
url: "https://michaelmacdonagh.net/"

